### ISSUE TITLE
Function which applies given velocity set to position

### ISSUE THREAD

**Issue by eduardfrankford** [MarcelDnB/discrete-pso#7]
![image](https://user-images.githubusercontent.com/44503138/70223434-03631580-174c-11ea-8b1b-570fdac492f2.png)

**Comment by marceljungle** [comment]
So here we need to apply all the elements from a Velocity like [(0,2),(0,3),(1,4)...] where 0 is "+" and 1 is "-" to a given Position like [4 3 5 6 8 7...] resulting a new Position [2 3 5 6 8 7], or im wrong? @eduardfrankford

**Comment by eduardfrankford** [comment]
yes i would understand it like that too :) 
@MarcelDnB
